#FROM is the first instruction
# we can use RHEL image but its licensed and not free. Hence we are using alternative almalinux from docker hub

FROM almalinux:9
# install nginx 
RUN dnf install nginx -y

# when we build this docker file, image will be generated alongwith nginx in addition to almalinux

